Django 4E/django_projects/mysite/ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = "ads"
success_url = reverse_lazy("ads:all")

urlpatterns = [
    path("", views.AdListView.as_view(), name="all"),
    path("ad/<int:pk>/", views.AdDetailView.as_view(), name="ad_detail"),
    path(
        "ad/create/",
        views.AdCreateView.as_view(success_url=success_url),
        name="ad_create",
    ),
    path(
        "ad/<int:pk>/update",
        views.AdUpdateView.as_view(success_url=success_url),
        name="ad_update",
    ),
    path(
        "ad/<int:pk>/delete",
        views.AdDeleteView.as_view(success_url=success_url),
        name="ad_delete",
    ),
]

Django 4E/django_projects/mysite/cats/urls.py
from django.urls import path

from . import views

app_name = "cats"

urlpatterns = [
    path("", views.CatList.as_view(), name="all"),
    path("main/create/", views.CatCreate.as_view(), name="cat_create"),
    path(
        "main/<int:pk>/update/", views.CatUpdate.as_view(), name="cat_update"
    ),
    path(
        "main/<int:pk>/delete/", views.CatDelete.as_view(), name="cat_delete"
    ),
    path("breed/", views.BreedList.as_view(), name="breed_list"),
    path("breed/create/", views.BreedCreate.as_view(), name="breed_create"),
    path(
        "breed/<int:pk>/update/",
        views.BreedUpdate.as_view(),
        name="breed_update",
    ),
    path(
        "breed/<int:pk>/delete/",
        views.BreedDelete.as_view(),
        name="breed_delete",
    ),
]

Django 4E/django_projects/mysite/mysite/urls.py
import pathlib

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    # application urls
    path("", TemplateView.as_view(template_name="home/main.html")),
    path("polls/", include("polls.urls")),
    path("hello/", include("hello.urls")),
    path("autos/", include("autos.urls")),
    path("cats/", include("cats.urls")),
    path("ads/", include("ads.urls")),
]

BASE_DIR = pathlib.Path(__file__).resolve().parent.parent

# serve the static html files
urlpatterns += [
    re_path(
        r"^site/(?P<path>.*)$",
        serve,
        {"document_root": BASE_DIR / "site", "show_indexes": True},
        name="site",
    ),
]

# serve the favicon
urlpatterns += [
    path(
        "favicon.ico",
        serve,
        {"path": "favicon.ico", "document_root": BASE_DIR / "home/static"},
    ),
]

# switch to social login if it is configured
try:
    from . import github_settings
    social_login = "registration/login_social.html"
    urlpatterns.insert(
        0,
        path(
            "accounts/login/",
            auth_views.LoginView.as_view(template_name=social_login),
        ),
    )
    print(f"Using {social_login} as the login template")

except:
    print("Using registration/login.html as the login template")

Django 4E/django_projects/mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class Breed(models.Model):
    name = models.CharField(
        max_length=200,
        validators=[
            MinLengthValidator(2, "Breed must be greater than 1 character")
        ],
    )

    def __str__(self):
        return self.name


class Cat(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators=[
            MinLengthValidator(2, "Nickname must be greater than 1 character")
        ],
    )
    weight = models.PositiveIntegerField()
    food = models.CharField(max_length=300)
    breed = models.ForeignKey("Breed", on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

Django 4E/django_projects/mysite/cats/forms.py
from django.forms import ModelForm

from .models import Breed


class BreedForm(ModelForm):
    class Meta:
        model = Breed
        fields = "__all__"

Django 4E/django_projects/mysite/cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import BreedForm
from .models import Breed, Cat


class CatList(LoginRequiredMixin, ListView):
    model = Cat
    fields = "__all__"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["breed_count"] = Breed.objects.count()

        return context


class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = "__all__"
    success_url = reverse_lazy("cats:all")


class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = "__all__"
    success_url = reverse_lazy("cats:all")


class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = "__all__"
    success_url = reverse_lazy("cats:all")


class BreedList(LoginRequiredMixin, View):
    def get(self, request):
        breed_list = Breed.objects.all()
        return render(
            request, "cats/breed_list.html", {"breed_list": breed_list}
        )


class BreedCreate(LoginRequiredMixin, View):
    template_name = "cats/breed_form.html"
    success_url = reverse_lazy("cats:all")

    def get(self, request):
        form = BreedForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = BreedForm(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {"form": form})

        form.save()
        return redirect(self.success_url)


class BreedUpdate(LoginRequiredMixin, View):
    model = Breed
    template_name = "cats/breed_form.html"
    success_url = reverse_lazy("cats:all")

    def get(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(instance=breed)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(request.POST, instance=breed)

        if not form.is_valid():
            return render(request, self.template_name, {"form": form})

        form.save()
        return redirect(self.success_url)


class BreedDelete(LoginRequiredMixin, View):
    model = Breed
    template_name= "cats/breed_confirm_delete.html"
    success_url = reverse_lazy("cats:all")

    def get(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        return render(request, self.template_name, {"breed": breed})

    def post(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        breed.delete()
        return redirect(self.success_url)

Django 4E/django_projects/mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block title %}Delete Breed{% endblock %}

{% block content %}
<h1>Delete Breed</h1>
<p>Are you sure you want to delete the breed "{{ breed }}"?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
</form>
{% endblock %}

Django 4E/django_projects/mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block title %}Breed Form{% endblock %}

{% block content %}
<h1>Add/Update a Breed</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
</form>
{% endblock %}

Django 4E/django_projects/mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}

{% block title %}Breed List{% endblock %}


{% block content %}
    <h1>Breed List</h1>
    {% if breed_list %}
    <ul>
        {% for breed in breed_list %}
        <li>
            {{ breed.name }}
            (
                <a href="{% url 'cats:breed_update' breed.id %}">Update</a> | 
                <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>
            )
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>There are no breeds in the library.</p>
    {% endif %}
    <p><a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
    <p><a href="{% url 'cats:all' %}">Back to cats</a></p>
{% endblock %}

Django 4E/django_projects/mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block title %}Delete Cat{% endblock %}

{% block content %}
<h1>Delete Cat</h1>
<p>Are you sure you want to delete the cat "{{ cat }}"?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
</form>
{% endblock %}

Django 4E/django_projects/mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block title %}Cat Form{% endblock %}

{% block content %}
<h1>Add/Update Cat</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
</form>
{% endblock %}

Django 4E/django_projects/mysite/cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}

{% block title %}Cat List{% endblock %}

{% block content %}
    <h1>Cat List</h1>
    {% if cat_list %}
    <ul>
        {% for cat in cat_list %}
        <li>
            {{ cat.nickname }} ({{ cat.breed}})
            (
                <a href="{% url 'cats:cat_update' cat.id %}">Update</a> | 
                <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>
            )
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>There are no cats in the library.</p>
    {% endif %}
    <p>
        {% if breed_count > 0 %}
        <a href="{% url 'cats:cat_create' %}">Add a cat</a>
        {% else %}
        Please add a breed before adding a cat.
        {% endif %}
    </p>
    <p>
        <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) | 
        <a href="{% url 'cats:breed_create' %}">Add a breed</a>
    </p>
{% endblock %}