Django 4E/django_projects/mysite/ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = "ads"
success_url = reverse_lazy("ads:all")

urlpatterns = [
    path("", views.AdListView.as_view(), name="all"),
    path("ad/<int:pk>/", views.AdDetailView.as_view(), name="ad_detail"),
    path(
        "ad/create/",
        views.AdCreateView.as_view(success_url=success_url),
        name="ad_create",
    ),
    path(
        "ad/<int:pk>/update",
        views.AdUpdateView.as_view(success_url=success_url),
        name="ad_update",
    ),
    path(
        "ad/<int:pk>/delete",
        views.AdDeleteView.as_view(success_url=success_url),
        name="ad_delete",
    ),
]

Django 4E/django_projects/mysite/mysite/urls.py
import pathlib

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    # application urls
    path("", TemplateView.as_view(template_name="home/main.html")),
    path("polls/", include("polls.urls")),
    path("hello/", include("hello.urls")),
    path("autos/", include("autos.urls")),
    path("cats/", include("cats.urls")),
    path("ads/", include("ads.urls")),
]

BASE_DIR = pathlib.Path(__file__).resolve().parent.parent

# serve the static html files
urlpatterns += [
    re_path(
        r"^site/(?P<path>.*)$",
        serve,
        {"document_root": BASE_DIR / "site", "show_indexes": True},
        name="site",
    ),
]

# serve the favicon
urlpatterns += [
    path(
        "favicon.ico",
        serve,
        {"path": "favicon.ico", "document_root": BASE_DIR / "home/static"},
    ),
]

# switch to social login if it is configured
try:
    from . import github_settings
    social_login = "registration/login_social.html"
    urlpatterns.insert(
        0,
        path(
            "accounts/login/",
            auth_views.LoginView.as_view(template_name=social_login),
        ),
    )
    print(f"Using {social_login} as the login template")

except:
    print("Using registration/login.html as the login template")

Django 4E/django_projects/mysite/ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings


class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[
            MinLengthValidator(2, "Title must be greater than 2 characters")
        ],
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

Django 4E/django_projects/mysite/ads/views.py
from .models import Ad
from .owner import (
    OwnerCreateView,
    OwnerDeleteView,
    OwnerDetailView,
    OwnerListView,
    OwnerUpdateView,
)


class AdListView(OwnerListView):
    model = Ad


class AdDetailView(OwnerDetailView):
    model = Ad

class AdCreateView(OwnerCreateView):
    model = Ad
    fields = ["title", "text", "price"]


class AdUpdateView(OwnerUpdateView):
    model = Ad
    fields = ["title", "text", "price"]


class AdDeleteView(OwnerDeleteView):
    model = Ad

Django 4E/django_projects/mysite/ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}

{% block content %}
<h1>Delete Artice</h1>
<p>Are you sure you want to delete "{{ ad.title }}"</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" value="No, don't delete." onclick="window.location.href='{% url 'ads:ad_detail' ad.id %}'; return false;">
</form>
{% endblock %}

Django 4E/django_projects/mysite/ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}

{% load humanize %}

{% block content %}
{{ ad.updated_at|naturaltime}}
{% if ad.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
<span>
    <h1>{{ ad.title }}</h1>
    <p>{{ ad.text }}</p>
    <p></p>
    <p><a href="{% url 'ads:all' %}">Back to all ads</a></p>
</span>
{% endblock %}

Django 4E/django_projects/mysite/ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}

{% load crispy_forms_tags %}

{% block content %}
<p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}'; return false;">
    </form>
</p>
{% endblock %}

Django 4E/django_projects/mysite/ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}

{% block content %}
<p>
    {% if ad_list %}
    <ul>
        {% for ad in ad_list %}
        <li>
            <a href="{% url 'ads:ad_detail' ad.id %}">{{ ad.title }}</a>
            {% if ad.owner == user %}
            (
                <a href="{% url 'ads:ad_update' ad.id %}">Edit</a> | 
                <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>
            )
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No ads are available.</p>
    {% endif %}
</p>
<p><a href="{% url 'ads:ad_create' %}">Add an Ad</a></p>
{% endblock %}